### ISSUE TITLE
[Discussion/feature request] -- Interactive GUI that change parameters by mouse

### ISSUE THREAD

**Issue by mizhozan** [francoisschwarzentruber/tikzzz#7]
Thanks for the app. I usually develop tikz in my IDE and have the visual feedback loop with something like `entr` in the background constantly watching the tex and re-compile.

However, one killer functionality is to being able to select node and re-position them or re-size them. This need some inter activeness. Currently there are app like ktikz that don't do much beyond specialized UI for compile tikz code. But the killer could be just have this inter activeness that compile the code, but associate some sort of handle to all parameters in the GUI in which when we change by moth the parameter changes in the code. I have no experience with web programming but it seems to me it's more suited to have this functionality based on JS/TS than let say QT, just share the thought.

**Comment by francoisschwarzentruber** [comment]
Thank you for your message. Yes, in tikzzz you can select a node and reposition it. By "parameters", do you need mean also colors, line width, etc. Currently, tikzzz only consider the position (coordinates) of nodes. We could also imagine to consider the relative positions wrt to other nodes etc. What do you think?

**Comment by mizhozan** [comment]
That's great part which I quite liked. I appreciate that direction, the only app that I know can come close is `tikzit` which has its own problems. I think those who bother with Tikz, appreciate the programming and text aspect of it. So personally I don't mind remove 'red' and type 'green' in the code part. However, having an app that give closer and easier visual feedback to manipulate already programmed Tikz is very benefitial. In this line:
1. Position of nodes and coordinates and ideally take capture relative +(a,b), ++(a,b) and calc library syntax.
2. Capture parameters such as size (of line), radius of circle, angle, etc.
4. A color picker would be nice to have, but not very essential I think

Though how to capture these parameters might be challenging (regex?). Just being able to do 1, I think is a very good step forward.

p.s. *Unfortunately, I couldn't run it (Archlinux). Tried to compile php72 from AUR and adopt phpize72 work instead of php-cli in debian. But since have no idea about web/server stuff, couldn't run it.*

**Comment by francoisschwarzentruber** [comment]
Hello! Sorry for the late answer... I was busy. I completely agree with you. Writing "green" is very easy. ;) Up to now, the tool only handles absolute coordinates! To be done:

- Relative +(a, b), ++(a, b)
- controls (a, b)
- polar coordinates (110:2cm)
- radius of circles, ellipses, etc.
- \begin{scope}...

regex are I think not sufficient. We need a decent parser. :)

PS: maybe I can help you. Which error do you get when running `./runlocally.sh`?

**Comment by francoisschwarzentruber** [comment]
PS2: You also have a running instance here: https://abcd.irisa.fr/tikzzz/

**Comment by mizhozan** [comment]
I just tested by the running instance and it's already usable, esp for quick prototyping. It also do what this issue asks for (I didn't got hands on experience on first try). That's great! So I'll close this as well. For improvement, I would like it capture as much as it can, the main one was the position of node elements which is already done, the other are size/color/attributes/etc which is out of scope for this thread.

Sorry for the installation part, I will do it later at first chance. I think it's a problem with my setup, I couldn't properly install php72-cli. So, I'll work on it later.
